### ISSUE TITLE
Slagen toevoegen

### ISSUE THREAD

**Issue by vhof** [bintzandt/CodeIgniter-Hydrofiel#13]
Torben kon geen slagen meer toevoegen aan een NSZK evenement, en ik vermoed dat dit komt omdat in [deze](https://github.com/bintzandt/CodeIgniter-Hydrofiel/blob/f4aafc31f9165f07487bf37dca3e5ffb9565cccb/application/views/beheer/agenda/edit_add.php#L127) line "id="slagen"" staat, wat misschien beter een class kan zijn. 

(ik wilde dus kijken of ik dit zelf op kon lossen omdat het best iets kleins is, maar heb nog steeds issues met de docker. Het is nu echter wel urgent geworden want het ONKS is al over een maand, dus daarom deze issue)

**Comment by bintzandt** [comment]
Hmm, ik denk dat dit dezelfde oorzaak heeft als bij het mailen. On it.
