### ISSUE TITLE
Login issue

### ISSUE THREAD

**Issue by vhof** [bintzandt/CodeIgniter-Hydrofiel#19]
Daphne: Ik kan de laatste dagen niet meer inloggen op de hydrofiel website. Alleen heel af en toe lukt het na 15x dezelfde inloggegevens invullen😅
Krijg ook geen melding van verkeerde gegevens, maar ik lijk iedere keer in een soort lus terecht te komen. Heb het ook al via meerdere apparaten en browsers geprobeerd

**Comment by bintzandt** [comment]
Is dit uiteindelijk nog opgelost? Ik heb niets van Daphne gehoord hierover namelijk.
