### ISSUE TITLE
Redirect to original page after redirect to login page

### ISSUE THREAD

**Issue by nielstenboom** [bintzandt/CodeIgniter-Hydrofiel#24]
**Situation:**

When clicking on a link where you need to be logged in for, you get redirected to the login page, after logging in you get the default page. 

**Desired behavior:**

Redirect back to the original clicked link after logging in. Can maybe implemented by adding a get parameter ?redirect=/agenda/id/51 to the login page or whatever to remember where to redirect to.

Would have opened a PR if the project was in Python ;)

**Comment by bintzandt** [comment]
Good one! I am going to pick this up this week :)

**Comment by bintzandt** [comment]
Fix should be live. Sorry it took longer 😛 

(I'm busy refactoring the codebase and changing the setup process so there are no changes on GitHub just yet...)

**Comment by bintzandt** [comment]
(I'm busy refactoring the codebase so there are no changes on GitHub just yet...)
